### ISSUE TITLE
Jitpack is down - breaking CI/CD

### ISSUE THREAD

**Issue by jvallwmp** [contentful/rich-text-renderer-java#33]
Jitpack is down right now:

https://github.com/jitpack/jitpack.io/issues/5337

Is there a chance this dependency could be moved to a more dependable repository? It's broken our CI/CD.

**Comment by paulbrejla** [comment]
For anyone coming here with the same issue, here is an ugly workaround (using the Kotlin dsl):
1. Extract the respective jars from your gradle cache directory if you are lucky and have not cleaned your cache yet :) - otherwise build from source.
2. Create a `lib` folder in your project root to store the jars.
3. Change your `repositories` config:
```
repositories {
    mavenCentral()
   // maven("https://jitpack.io")
    flatDir {
        dirs("lib")
    }
}
```
4. Reference the dependencies in your `dependencies`:
```
    implementation("com.github.contentful.rich-text-renderer-java:html:1.4.0")
    implementation("com.github.contentful.rich-text-renderer-java:core:1.4.0")
```
5. Commit these files.
